FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy everything from project root
COPY . .

# Set Python path
ENV PYTHONPATH=/app
CMD ["python3", "./backend/app/services/kafka_consumer.py"]